aws-samples/amazon-ivs-player-web-sample

- README.md
Add Repl.it badge and update Repl.it link in Live Demo section to non-user-scoped URL.
> Update README.md with Repl.it badge

- README.md
Updating the README with step by step instructions for setting up the repl.it live demo.
> Update README.md with repl.it instructions

- package-lock.json
- package.json
- samples/cloud-player/cloud-player.html
> update to 1.4.0

- README.md
- samples/common/form-control.ts
- samples/videojs/videojs.ts
This PR fixes the load button on the video.js sample page, and updates the default stream to one with closed captions.
> Update videojs page

- package-lock.json
- package.json
- samples/cloud-player/cloud-player.html
Player version update to 1.6.1
> Update to 1.6.1

- .npmrc
- package-lock.json
- package.json
- samples/cloud-player/cloud-player.html
> Update version to 1.7.0

- package-lock.json
- package.json
- samples/npm-sdk/npm-sdk.ts
- webpack.config.js
- Updates packages to resolve security warnings from NPM
> Update to webpack 5 to resolve dep security issues

- package-lock.json
- package.json
- samples/cloud-player/cloud-player.html
- samples/cloud-player/cloud-player.ts
- samples/npm-sdk/npm-sdk.ts
* Update the IVS cloud player example to 1.8.0
* Update the npm player example to 1.8.0
* Fix small controls issue where player reference was undefined
> 1.8.0 IVS Release Updates

- package-lock.json
- package.json
- samples/cloud-player/cloud-player.html
Upgrade to IVS Web Player 1.10.0.
> chore: upgrade to 1.10.0

- package-lock.json
- package.json
- samples/cloud-player/cloud-player.html
* Update IVS package versions to 1.11.0
> chore: release 1.11.0

- package-lock.json
- package.json
- samples/cloud-player/cloud-player.html
- Update IVS package versions to 1.13.0
> chore: release 1.13.0

- package-lock.json
- package.json
- samples/cloud-player/cloud-player.html
> chore:release 1.16.0

- package-lock.json
- package.json
- samples/cloud-player/cloud-player.html
> chore:release 1.18.0

- package-lock.json
- package.json
- samples/cloud-player/cloud-player.html
> chore:release 1.19.0

- package-lock.json
- package.json
- samples/cloud-player/cloud-player.html
> chore: release 1.21.0

- package-lock.json
- package.json
- samples/cloud-player/cloud-player.html
Updating samples to use latest release
> chore: release 1.23.0

- README.md
- samples/index.html
- samples/service-worker/amazon-ivs-service-worker-loader.js
- samples/service-worker/service-worker.html
- samples/service-worker/service-worker.ts
- webpack.config.js
This adds an example of setting up and configuring a service worker for lower latency playback on iOS Safari.
> samples: add service worker example

- package-lock.json
- package.json
- samples/cloud-player/cloud-player.html
- samples/service-worker/service-worker.html
Update IVS Player SDK to `1.25.0`
> chore: release 1.25.0

- package-lock.json
- package.json
- samples/cloud-player/cloud-player.html
- samples/service-worker/service-worker.html
> chore: release 1.28.0

- package-lock.json
- package.json
- samples/cloud-player/cloud-player.html
- samples/service-worker/service-worker.html
> chore: release 1.29.0

- package-lock.json
- package.json
- samples/cloud-player/cloud-player.html
- samples/service-worker/service-worker.html
> Player version 1.30.0

- package-lock.json
- package.json
- samples/cloud-player/cloud-player.html
- samples/service-worker/service-worker.html
Updating SDK version to `1.31.0`
> chore: release 1.31.0

- package-lock.json
- package.json
- samples/cloud-player/cloud-player.html
- samples/service-worker/service-worker.html
> chore: release 1.34.1

- package-lock.json
- package.json
- samples/cloud-player/cloud-player.html
- samples/service-worker/service-worker.html
> chore:release 1.35.0

- package-lock.json
- package.json
- samples/cloud-player/cloud-player.html
- samples/service-worker/service-worker.html
> Update player to 1.36.0

- package-lock.json
- package.json
- samples/cloud-player/cloud-player.html
- samples/service-worker/amazon-ivs-service-worker-loader.js
- samples/service-worker/service-worker.html
Updating the Player SDK to `1.37.0`
> chore:release 1.37.0

- package-lock.json
- package.json
- samples/cloud-player/cloud-player.html
- samples/service-worker/service-worker.html
> chore:release 1.38.0

- package-lock.json
- package.json
- samples/cloud-player/cloud-player.html
- samples/service-worker/service-worker.html
> Update to 1.39.0
